name: Build test

on:
  push:
    branches:
      - YML-Pipeline
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Compiling SCIANTIX"
          make
          ls
          cd bin
          echo "in bin"
          

