name: Python application test

on:
  push:
    branches:
      - YML-Pipeline
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Display Python version
        run: python -V ; pip -V

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install numpy matplotlib scipy scikit-learn

      - name: Build
        run: |
          echo "Compiling SCIANTIX"
          make
          ls
          cd bin
          echo "in bin"
          ls

      - name: Run tests
        run: |
          source venv/bin/activate
          python ./regression/regression.py 
